import SwiftUI

/// "QUICK TAKE" section with AI-generated analysis paragraph.
struct QuickTakeSectionView: View {
    let quickTake: QuickTake

    var body: some View {
        VStack(alignment: .leading, spacing: MPSpacing.card) {
            SectionHeaderView(emoji: "\u{26A1}", title: "Quick Take")

            VStack(alignment: .leading, spacing: MPSpacing.item) {
                // AI analysis paragraph
                Text(quickTake.text)
                    .font(MPFont.body())
                    .foregroundStyle(MPColor.textSecondary)
                    .lineSpacing(5)
                    .fixedSize(horizontal: false, vertical: true)

                // Attribution
                HStack(spacing: MPSpacing.tight) {
                    Image(systemName: "sparkles")
                        .font(.system(size: 10))
                        .foregroundStyle(MPColor.accent.opacity(0.6))

                    Text("Generated by \(quickTake.provider)")
                        .font(MPFont.caption())
                        .foregroundStyle(MPColor.textTertiary)
                }
                .padding(.top, MPSpacing.tight)
            }
            .cardStyle()
            .padding(.horizontal, MPSpacing.card)
        }
    }
}

#Preview {
    ZStack {
        MPColor.background.ignoresSafeArea()
        ScrollView {
            QuickTakeSectionView(
                quickTake: QuickTake(
                    text: "Markets showed mixed signals today with tech leading gains while energy lagged. The S&P 500 managed to close above its 50-day moving average, suggesting continued bullish momentum. Earnings season has been broadly positive with 72% of S&P 500 companies beating estimates. Watch for Friday's jobs report as a potential catalyst.",
                    provider: "Claude API",
                    generatedAt: Date()
                )
            )
        }
    }
}
