name: MarketPulse
options:
  bundleIdPrefix: com.marketpulse
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_CFBundleDisplayName: MarketPulse
    ENABLE_USER_SCRIPT_SANDBOXING: YES

targets:
  MarketPulse:
    type: application
    platform: iOS
    sources:
      - path: MarketPulse
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.marketpulse.app
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: MarketPulse/MarketPulse.entitlements
      properties:
        com.apple.security.app-sandbox: true
        keychain-access-groups:
          - "$(AppIdentifierPrefix)com.marketpulse"
